Adds new main for swift-curses-mock2
At present, this breaks my project:

    % swift run swift-curses-mock2
    /Users/rick/Projects/wordle-cli/.build/checkouts/SwiftCursesTerm/Sources/SwiftCursesTerm/SwiftCursesTerm.swift:1:8: error: cannot load module 'Curses' as 'curses'
    import curses
           ^
    /Users/rick/Projects/wordle-cli/.build/checkouts/SwiftCursesTerm/Sources/SwiftCursesTerm/SwiftCursesTerm.swift:1:8: error: cannot load module 'Curses' as 'curses'
    import curses
           ^
    /Users/rick/Projects/wordle-cli/.build/checkouts/SwiftCursesTerm/Sources/SwiftCursesTerm/SwiftCursesTerm.swift:1:8: error: cannot load module 'Curses' as 'curses'
    import curses
           ^

    error: fatalError